{
 "title": "Fase D — Dashboard",
 "description": "Parte de gráfica de Grafana para el proyecto de Marzo",
 "time": { "from": "2024-12-03T10:32:38.214Z", "to": "2026-03-07T01:41:07.567Z" },
 "templating": {
  "list": [
   {
    "name": "sensor_temperatura_id",
    "query": {
     "query": "SELECT DISTINCT entity_id \r\nFROM \"ltss\" \r\nWHERE (entity_id LIKE '%_temperature%' OR entity_id LIKE '%_temperatura%')\r\n  AND entity_id NOT LIKE '%humidity%'\r\n  AND entity_id NOT LIKE '%pressure%'\r\n  AND entity_id NOT LIKE '%battery%'\r\n  AND entity_id NOT LIKE '%manises%'\r\n  AND entity_id NOT LIKE '%mislata%'\r\n  AND entity_id NOT LIKE '%device%'"
    }
   },
   {
    "name": "sensor_humedad_id",
    "query": {
     "query": "SELECT DISTINCT entity_id \r\nFROM \"ltss\" \r\nWHERE (entity_id LIKE '%_humidity%' \r\n       OR entity_id LIKE '%_humedad%')\r\n  AND entity_id NOT LIKE '%pressure%'\r\n  AND entity_id NOT LIKE '%battery%'\r\n  AND entity_id NOT LIKE '%manises%'\r\n  AND entity_id NOT LIKE '%mislata%'\r\n  AND entity_id NOT LIKE '%device%';"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatura de los sensores en un rango de tiempo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  \"time\" AS time,\r\n  entity_id AS metric,\r\n  state::double precision AS value\r\nFROM ltss\r\nWHERE $__timeFilter(\"time\")\r\n  AND entity_id IN (${sensor_temperatura_id:sqlstring})\r\n  AND state IS NOT NULL\r\n  AND state <> ''\r\n  AND state <> 'unavailable'\r\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "GAugge con la temperatura media de varios sensores",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  AVG(state::double precision) AS value\r\nFROM ltss\r\nWHERE $__timeFilter(\"time\")\r\n  AND entity_id IN (${sensor_temperatura_id:sqlstring})\r\n  AND state IS NOT NULL\r\n  AND state <> ''\r\n  AND state <> 'unavailable'"
    }
   ]
  },
  {
   "title": "Humedad de los sensores en un rango de tiempo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  \"time\" AS time,\r\n  entity_id AS metric,\r\n  state::double precision AS value\r\nFROM ltss\r\nWHERE $__timeFilter(\"time\")\r\n  AND entity_id IN (${sensor_humedad_id:sqlstring})\r\n  AND state IS NOT NULL\r\n  AND state <> ''\r\n  AND state <> 'unavailable'\r\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "GAugge con la humedad media de varios sensores",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  AVG(state::double precision) AS value\r\nFROM ltss\r\nWHERE $__timeFilter(\"time\")\r\n  AND entity_id IN (${sensor_humedad_id:sqlstring})\r\n  AND state IS NOT NULL\r\n  AND state <> ''\r\n  AND state <> 'unavailable'"
    }
   ]
  }
 ]
}