{
 "title": "Sensores Aula",
 "time": { "from": "2025-10-23T22:00:00.000Z", "to": "2025-10-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "Temperatura",
    "query": "SELECT entity_id\nFROM ltss\nWHERE entity_id IN (\n  'sensor.sensor_temperatura_1_temperature',\n  'sensor.sensor_temperatura_2_temperature',\n  'sensor.sensor_temperatura_3_temperature',\n  'sensor.sensor_temperatura_4_temperature'\n)\nGROUP BY entity_id\nORDER BY entity_id"
   },
   {
    "name": "sensor_h",
    "label": "Humedad",
    "query": "SELECT entity_id\nFROM ltss\nWHERE entity_id IN (\n  'sensor.sensor_temperatura_1_humidity',\n  'sensor.sensor_temperatura_2_humidity',\n  'sensor.sensor_temperatura_3_humidity',\n  'sensor.sensor_temperatura_4_humidity'\n)\nGROUP BY entity_id\nORDER BY entity_id"
   }
  ]
 },
 "panels": [
  {
   "title": "Sensor principal de temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \n  \"time\" as time,\n  entity_id as metric,\n  state::double precision as value\nFROM ltss\nWHERE entity_id IN (\n\n  'sensor.sensor_temperatura_2_temperature'\n)\nAND state NOT IN ('unavailable')\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Sensor principal de Humedad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \n  \"time\" as time,\n  entity_id as metric,\n  state::double precision as value\nFROM ltss\nWHERE entity_id IN (\n\n  'sensor.sensor_temperatura_2_humidity'\n)\nAND state NOT IN ('unavailable')\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  \"time\" AS time,\n  state::double precision AS \"value\",\n  entity_id\nFROM ltss\nWHERE $__timeFilter(\"time\")\nAND entity_id IN (${sensor:sqlstring})\nAND state IS NOT NULL\nAND state <> ''\nAND state <> 'unavailable'\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Temperatura Media",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \n  avg(state::double precision) as value\nFROM ltss\nWHERE entity_id IN (${sensor:singlequote})\nAND state NOT IN ('unavailable','unknown');"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  \"time\" AS time,\n  state::double precision AS \"value\",\n  entity_id\nFROM ltss\nWHERE $__timeFilter(\"time\")\nAND entity_id IN (${sensor_h:sqlstring})\nAND state IS NOT NULL\nAND state <> ''\nAND state <> 'unavailable'\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Humedad Media",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \n  avg(state::double precision) as value\nFROM ltss\nWHERE entity_id IN (${sensor_h:singlequote})\nAND state NOT IN ('unavailable','unknown');"
    }
   ]
  }
 ]
}