FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.docker.txt /app/requirements.docker.txt
RUN pip install --no-cache-dir -r /app/requirements.docker.txt

COPY src /app/src
COPY src/model /app/src/model

ENV PORT=8000

EXPOSE 8000

CMD ["python", "-m", "src.api"]

